  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/security_jwt
      username: root
      password: P@ssW0rd32!
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days

